#pragma once

#include "HJMacros.h"

typedef enum HJRenderVideoCaptureEvent
{
    HJVIDEOCAPTURE_EVENT_NONE = 0,
    HJVIDEOCAPTURE_EVENT_ERROR_DEFAULT,
    HJVIDEOCAPTURE_EVENT_ERROR_UPDATE,
    HJVIDEOCAPTURE_EVENT_ERROR_DRAW,
    HJVIDEOCAPTURE_EVENT_ERROR_VIDEOCAPTURE_INIT,
    HJVIDEOCAPTURE_EVENT_ERROR_PNGSEQ_INIT,
    HJVIDEOCAPTURE_EVENT_PNGSEQ_COMPLETE,
} HJRenderVideoCaptureEvent;
HJEnumToStringFuncDecl(HJRenderVideoCaptureEvent);


