#pragma once

#include "HJMacros.h"

typedef enum HJVideoRenderGraphEvent
{
    HJVIDEORENDERGRAPH_EVENT_NONE = 0,
    HJVIDEORENDERGRAPH_EVENT_ERROR_DEFAULT,
    HJVIDEORENDERGRAPH_EVENT_ERROR_UPDATE,
    HJVIDEORENDERGRAPH_EVENT_ERROR_DRAW,
    HJVIDEORENDERGRAPH_EVENT_ERROR_INIT,
    HJVIDEORENDERGRAPH_EVENT_ERROR_PNGSEQ_INIT,
    HJVIDEORENDERGRAPH_EVENT_NEED_SURFACE,
    HJVIDEORENDERGRAPH_EVENT_PNGSEQ_COMPLETE,
} HJVideoRenderGraphEvent;
HJEnumToStringFuncDecl(HJVideoRenderGraphEvent);

typedef enum HJComPlayerEvent
{
	HJCOMPLAYER_EVENT_NONE = 0,
	HJCOMPLAYER_DEFAULT_ERROR,
    HJCOMPLAYER_DEMUX_READY,
    HJCOMPLAYER_RENDER_FRAME,
} HJComPlayerEvent;
HJEnumToStringFuncDecl(HJComPlayerEvent);

