#pragma once

#include "HJMacros.h"

typedef enum HJPluginNotifyType
{
    HJ_PLUGIN_NOTIFY_NONE = 0,
    HJ_PLUGIN_NOTIFY_EOF = 1,

    HJ_PLUGIN_NOTIFY_ERROR_MUXER_INIT = 100,
    HJ_PLUGIN_NOTIFY_ERROR_MUXER_WRITEFRAME = 101,

    HJ_PLUGIN_NOTIFY_ERROR_CODEC_INIT = 110,
    HJ_PLUGIN_NOTIFY_ERROR_CODEC_RUN = 111,
    HJ_PLUGIN_NOTIFY_ERROR_CODEC_GETFRAME = 112,
    HJ_PLUGIN_NOTIFY_ERROR_CODEC_INVALID_DATA = 113,

    HJ_PLUGIN_NOTIFY_ERROR_AUDIOCONVERTER_CONVERT = 120,
    HJ_PLUGIN_NOTIFY_ERROR_AUDIOFIFO_ADDFRAME = 121,

    HJ_PLUGIN_NOTIFY_ERROR_CAPTURER_GETFRAME = 130,

    HJ_PLUGIN_NOTIFY_ERROR_DEMUXER_INIT = 140,
    HJ_PLUGIN_NOTIFY_ERROR_DEMUXER_GETFRAME = 141,
    HJ_PLUGIN_NOTIFY_ERROR_DEMUXER_SEEK = 142,
    HJ_PLUGIN_NOTIFY_DEMUXER_EOF = 145,
    HJ_PLUGIN_NOTIFY_DEMUXER_DURATION = 146,

    HJ_PLUGIN_NOTIFY_VIDEORENDER_FRAME = 150,
    HJ_PLUGIN_NOTIFY_VIDEORENDER_FIRST_FRAME = 151,
    HJ_PLUGIN_NOTIFY_VIDEORENDER_EOF = 152,

    HJ_PLUGIN_NOTIFY_ERROR_AUDIORENDER_INIT = 160,
    HJ_PLUGIN_NOTIFY_ERROR_AUDIORENDER_RUNTASK = 161,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_START_PLAYING = 162,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_STOP_PLAYING = 163,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_START_BUFFERING = 164,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_STOP_BUFFERING = 165,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_EOF = 166,
    HJ_PLUGIN_NOTIFY_AUDIORENDER_FRAME = 167,

    HJ_PLUGIN_NOTIFY_AUDIOCACHE_DURATION = 170,
    HJ_PLUGIN_NOTIFY_AUTODELAY_PARAMS = 171,

    HJ_PLUGIN_NOTIFY_PLUGIN_SETINFOS = 172,

    HJ_PLUGIN_NOTIFY_PLUGIN_SEI_INFOS = 180,
    HJ_PLUGIN_NOTIFY_PLUGIN_SEI_REQUIRE = 181,

    HJ_PLUGIN_NOTIFY_ERROR_AUDIOMIXER_INIT = 190,
    HJ_PLUGIN_NOTIFY_ERROR_AUDIOMIXER_MIXFRAME = 191,
    HJ_PLUGIN_NOTIFY_AUDIOMIXER_INPUT_STARVED = 192,
    HJ_PLUGIN_NOTIFY_AUDIOMIXER_INPUT_RECOVERED = 193,
    HJ_PLUGIN_NOTIFY_AUDIOMIXER_INPUT_EOF = 194,

} HJPluginNotifyType;
HJEnumToStringFuncDecl(HJPluginNotifyType);
/*
typedef enum HJPluginInformationType
{
    HJ_PLUGIN_SETINFO_NONE = 0,

//    HJ_PLUGIN_SETINFO_PLUGIN_status,
//    HJ_PLUGIN_SETINFO_PLUGIN_duqueSize,
//    HJ_PLUGIN_SETINFO_PLUGIN_audioDuration,
//    HJ_PLUGIN_SETINFO_PLUGIN_videoKeyFrames,
//    HJ_PLUGIN_SETINFO_PLUGIN_videoFrames,

//    HJ_PLUGIN_SETINFO_AUDIODECODER_audioDuration,
//    HJ_PLUGIN_SETINFO_AUDIORENDER_audioDuration,
//    HJ_PLUGIN_SETINFO_DROPPING_audioDuration,

//    HJ_PLUGIN_SETINFO_VIDEODECODER_frameSize,
//    HJ_PLUGIN_SETINFO_VIDEORENDER_frameSize,

//    HJ_PLUGIN_SETINFO_DROPPING_videoKeyFrames,

//    HJ_PLUGIN_SETINFO_DEMUXER_mediaType,

    HJ_PLUGIN_GETINFO_NONE = 1000,

//    HJ_PLUGIN_GETINFO_hasAudio,

//    HJ_PLUGIN_GETINFO_DEMUXER_canDeliverToOutputs,
//    HJ_PLUGIN_GETINFO_VIDEODECODER_canDeliverToOutputs,
//    HJ_PLUGIN_GETINFO_DROPPING_canDeliverToOutputs

} HJPluginInformationType;
*/
