#pragma once

#include "HJMacros.h"

typedef enum HJPluginNofityType
{
    HJ_PLUGIN_NOTIFY_NONE = 0,

    HJ_PLUGIN_NOTIFY_ERROR_MUXER_INIT = 100,
    HJ_PLUGIN_NOTIFY_ERROR_MUXER_WRITEFRAME = 101,

    HJ_PLUGIN_NOTIFY_ERROR_CODEC_RUN = 110,
    HJ_PLUGIN_NOTIFY_ERROR_CODEC_GETFRAME = 111,

    HJ_PLUGIN_NOTIFY_ERROR_AUDIOFIFO_ADDFRAME = 120,

    HJ_PLUGIN_NOTIFY_ERROR_CAPTURER_GETFRAME = 130

} HJPluginNofityType;
HJEnumToStringFuncDecl(HJPluginNofityType);
