set(PROJ_NAME MBEDTLS)
set(LIBPROJ_NAME LIB${PROJ_NAME})
set(PROJ_LIB_NAME mbedtls)
set(PROJ_DIR_NAME mbedtls)
set(PROJ_HEADER mbedtls/mbedtls_config.h)

find_path(
  ${PROJ_NAME}_INCLUDE_DIR
  NAMES ${PROJ_HEADER}
  HINTS ${HJ_DEPS_DIR}/${PROJ_DIR_NAME}
  PATH_SUFFIXES include)
get_filename_component(${PROJ_NAME}_DIR ${${PROJ_NAME}_INCLUDE_DIR} DIRECTORY)
# message(STATUS "HJ_DEPS_DIR=${HJ_DEPS_DIR}, ${PROJ_NAME}_INCLUDE_DIR=${${PROJ_NAME}_INCLUDE_DIR}, ${PROJ_NAME}_DIR:${${PROJ_NAME}_DIR}")

find_library(
  ${PROJ_NAME}_LIB
  NAMES ${${PROJ_NAME}_LIBRARIES} ${PROJ_LIB_NAME} lib${PROJ_LIB_NAME}
  HINTS ${HJ_DEPS_DIR}/${PROJ_DIR_NAME} ${HJ_DEPS_DIR}/${PROJ_DIR_NAME}/lib
  PATH_SUFFIXES ${ARCHS_NAME})
get_filename_component(${PROJ_NAME}_LIB_DIR ${${PROJ_NAME}_LIB} DIRECTORY)
# message(STATUS "${PROJ_NAME}_LIB=${${PROJ_NAME}_LIB} ${PROJ_NAME}_LIB_DIR=${${PROJ_NAME}_LIB_DIR}")

find_library(
  ${PROJ_NAME}_LIB_MBEDCRYPTO
  NAMES ${${PROJ_NAME}_LIBRARIES} mbedcrypto libmbedcrypto
  HINTS ${HJ_DEPS_DIR}/${PROJ_DIR_NAME} ${HJ_DEPS_DIR}/${PROJ_DIR_NAME}/lib
  PATH_SUFFIXES ${ARCHS_NAME})
# message(STATUS "${PROJ_NAME}_LIB_MBEDCRYPTO=${${PROJ_NAME}_LIB_MBEDCRYPTO}}")

find_library(
  ${PROJ_NAME}_LIB_MBEDX509
  NAMES ${${PROJ_NAME}_LIBRARIES} mbedx509 libmbedx509
  HINTS ${HJ_DEPS_DIR}/${PROJ_DIR_NAME} ${HJ_DEPS_DIR}/${PROJ_DIR_NAME}/lib
  PATH_SUFFIXES ${ARCHS_NAME})
# message(STATUS "${PROJ_NAME}_LIB_MBEDX509=${${PROJ_NAME}_LIB_MBEDX509}}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(${LIBPROJ_NAME} DEFAULT_MSG ${PROJ_NAME}_INCLUDE_DIR ${PROJ_NAME}_LIB ${PROJ_NAME}_LIB_MBEDCRYPTO ${PROJ_NAME}_LIB_MBEDX509)
mark_as_advanced(${PROJ_NAME}_INCLUDE_DIR ${PROJ_NAME}_LIB ${PROJ_NAME}_LIB_MBEDCRYPTO ${PROJ_NAME}_LIB_MBEDX509)

if(${LIBPROJ_NAME}_FOUND)
  set(${LIBPROJ_NAME}_INCLUDE_DIRS ${${PROJ_NAME}_INCLUDE_DIR})
  set(${LIBPROJ_NAME}_LIBRARIES ${${PROJ_NAME}_LIB} ${${PROJ_NAME}_LIB_MBEDCRYPTO} ${${PROJ_NAME}_LIB_MBEDX509})
  # message(STATUS "${LIBPROJ_NAME}_INCLUDE_DIRS=${${LIBPROJ_NAME}_INCLUDE_DIRS}, ${LIBPROJ_NAME}_LIBRARIES:${${LIBPROJ_NAME}_LIBRARIES}")

  add_library(${LIBPROJ_NAME} INTERFACE)
  target_link_libraries(${LIBPROJ_NAME} INTERFACE ${${LIBPROJ_NAME}_LIBRARIES})
  target_include_directories(${LIBPROJ_NAME} INTERFACE ${${LIBPROJ_NAME}_INCLUDE_DIRS})
endif()
