#pragma once

#include "HJMacros.h"

typedef enum HJVideoRenderGraphEvent
{
    HJVIDEORENDERGRAPH_EVENT_NONE = 0,
    HJVIDEORENDERGRAPH_EVENT_ERROR_DEFAULT,
    HJVIDEORENDERGRAPH_EVENT_ERROR_UPDATE,
    HJVIDEORENDERGRAPH_EVENT_ERROR_DRAW,
    HJVIDEORENDERGRAPH_EVENT_ERROR_INIT,
    HJVIDEORENDERGRAPH_EVENT_ERROR_PNGSEQ_INIT,
    HJVIDEORENDERGRAPH_EVENT_NEED_SURFACE,
    HJVIDEORENDERGRAPH_EVENT_PNGSEQ_COMPLETE,
    HJVIDEORENDERGRAPH_EVENT_FACEU_ERROR,
    HJVIDEORENDERGRAPH_EVENT_FACEU_COMPLETE,

    HJVIDEORENDERGRAPH_EVENT_INIT_SUCCESS,
    HJVIDEORENDERGRAPH_EVENT_INIT_FAILED,

    HJVIDEORENDERGRAPH_EVENT_NodeCreateSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeCreateFailed,

    HJVIDEORENDERGRAPH_EVENT_NodeConnectSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeConnectFailed,

    HJVIDEORENDERGRAPH_EVENT_NodeDisconnectSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeDisconnectFailed,

    HJVIDEORENDERGRAPH_EVENT_NodeDeleteSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeDeleteFailed,

    HJVIDEORENDERGRAPH_EVENT_NodeEnableSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeEnableFailed,

    HJVIDEORENDERGRAPH_EVENT_NodeLinkInfoChangeSuccess,
    HJVIDEORENDERGRAPH_EVENT_NodeLinkInfoChangeFailed,


} HJVideoRenderGraphEvent;
HJEnumToStringFuncDecl(HJVideoRenderGraphEvent);

typedef enum HJComPlayerEvent
{
	HJCOMPLAYER_EVENT_NONE = 0,
	HJCOMPLAYER_DEFAULT_ERROR,
    HJCOMPLAYER_DEMUX_READY,
    HJCOMPLAYER_RENDER_FRAME,
} HJComPlayerEvent;
HJEnumToStringFuncDecl(HJComPlayerEvent);

